### ISSUE TITLE
The performance on MS COCO Val5000 

### ISSUE THREAD

**Issue by eriche2016** [ruotianluo/neuraltalk2.pytorch#1]
Hi, very good job. Can you give the final performance that this code can achieve on MS COCO validation-5000 comparing to karpathy's neuraltalk2?

**Comment by ruotianluo** [comment]
~0.9 cider

**Comment by eriche2016** [comment]
thanks for your reply.

**Comment by brisker** [comment]
@ruotianluo 
I run the code but spend more than 1 hour for 1 epoch training, and the code consumes around only 2.8gb memory, anything wrong? Why is it so slow?  I am using titan x gpu.

**Comment by ruotianluo** [comment]
What's the output in the screen: how long is each iteration and how long it take to read data. And, 2.8 sounds reasonable.

**Comment by brisker** [comment]
@ruotianluo 
jcc@jcc:~/research/neuraltalk2.pytorch$ python train.py --input_json coco/cocotalk.json --input_fc_dir data/cocotalk_fc --input_att_dir data/cocotalk_att --input_label_h5 data/cocotalk_label.h5 --beam_size 1 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --save_checkpoint_every 6000 --val_images_use 5000
DataLoader loading json file:  coco/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocotalk_fc data/cocotalk_att data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Read data: 0.6934030056
iter 0 (epoch 0), train_loss = 9.160, time/batch = 0.842
Read data: 0.248576879501
iter 1 (epoch 0), train_loss = 9.108, time/batch = 0.249
Read data: 0.0909299850464
iter 2 (epoch 0), train_loss = 9.037, time/batch = 0.236
Read data: 0.110040903091
iter 3 (epoch 0), train_loss = 8.957, time/batch = 0.213
Read data: 0.105381011963
iter 4 (epoch 0), train_loss = 8.844, time/batch = 0.210
Read data: 0.11315703392
iter 5 (epoch 0), train_loss = 8.730, time/batch = 0.231

**Comment by brisker** [comment]
@ruotianluo 
` parser.add_argument('--caption_model', type=str, default="show_tell",`
“show_tell” is corresponding to neuraltalk2 model of karpathy, right？(sorry, new  to image caption)

**Comment by ruotianluo** [comment]
Read data is a little bit too long.
