### ISSUE TITLE
Potential Issue of using multi-gpu

### ISSUE THREAD

**Issue by chihyaoma** [ruotianluo/neuraltalk2.pytorch#13]
Hey, thanks for this amazing repo. 

I was reading through your code, and I think there might be a potential issue for using multiple GPU with `torch.nn.DataParallel`

Particularly, you break the procedure when sentences reach the end (by checking their sum)
```python
# https://github.com/ruotianluo/neuraltalk2.pytorch/blob/master/models/AttModel.py#L90-L91
if i >= 1 and seq[:, i].data.sum() == 0:
    break

# I am using AttModel.py as an example, but it should be the same to other models
```
When forward passing the model, the data in mini-batch will be divided and send into individual GPUs, there could be a case where the output on one GPU is shorter than the others. This will result in an error when collecting output from all GPUs, since their dimension mismatch.

Is there any particular reason why you break the process, instead of letting it run to the end (let the for loop finish)?

**Comment by ruotianluo** [comment]
It's just inherited from original neuraltalk2 repository. It potentially will speed up a little bit.
If you want to use DataParallel, you can definitely comment out these two lines; I don't think it affect the result.

**Comment by chihyaoma** [comment]
Thanks for the quick response. I am closing this issue now.
