### ISSUE TITLE
TensorBoard Problem

### ISSUE THREAD

**Issue by ahkarami** [ruotianluo/neuraltalk2.pytorch#17]
Dear @ruotianluo, 
When I run the `train.py` code for MS-COCO data set, I have faced the following error:
`Traceback (most recent call last):
  File "train.py", line 204, in <module>
    train(opt)
  File "train.py", line 152, in train
    for k,v in lang_stats.items():
AttributeError: 'NoneType' object has no attribute 'items'
Terminating BlobFetcher`
this error occurred, when the evaluation process is running (i.e., save_checkpoint process). 
When I have commented the `# Write validation result into summary` part in your `train.py` code, then everything were correct, unless I can't seen chart in the TensorBoard.

**Comment by ruotianluo** [comment]
I see, the reason is your language_eval is 0. So lang_stats is None.

**Comment by ahkarami** [comment]
Oh, OK. Thank you very much.
