### ISSUE TITLE
Some confusion about adaptive attention model

### ISSUE THREAD

**Issue by a380922457** [ruotianluo/neuraltalk2.pytorch#19]
First, thanks so much for contributing such great codes.
However,I get some questions when I review code of the adaptive attention model.According to the paper "Knowing When to Look", LSTM only receive the word vector Xt and the previous hidden state Ht-1,instead of the image vector,but your code includes the image vector when building the LSTM.
Would you please explain it ?

**Comment by ruotianluo** [comment]
https://github.com/jiasenlu/AdaptiveAttention/blob/master/misc/LSTM.lua

**Comment by a380922457** [comment]
Fine... very interesting,still don't know why.
gt = σ(W*xt +Wh*h)  (1)  if g includes image vector
st = gt ⊙tanh(mt) 
cˆt = β*s + (1 − β)*c  if β = 1,won't it  still use the information of image?

**Comment by ruotianluo** [comment]
Eh, I'm not very familiar with this model? What about ask under the author's repository?

**Comment by a380922457** [comment]
OK,thank you very much
