### ISSUE TITLE
One problem during the training process

### ISSUE THREAD

**Issue by lxtGH** [ruotianluo/neuraltalk2.pytorch#20]
preprocessing steps are both ok, but when I am trainning the model after epoch 0, 

```
evaluating validation preformance... -1/5000 (2.649871)
Traceback (most recent call last):
  File "train.py", line 204, in <module>
    train(opt)
  File "train.py", line 152, in train
    for k,v in lang_stats.items():
AttributeError: 'NoneType' object has no attribute 'items'
Terminating BlobFetcher
```
seems like codes in line 138-140 in file **eval_utils.py** meet the problem
`lang_stats = None
    if lang_eval == 1:
        lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)`
I am new to pytorch

**Comment by ruotianluo** [comment]
Did you download coco-caption.

**Comment by lxtGH** [comment]
sorry, I forget. I try it now , Thanks you very much for the nice code and immediate respondence !!!

**Comment by lxtGH** [comment]
But I still got this error after I added coco-caption into the main diretory 。

**Comment by ruotianluo** [comment]
did you set language_eval to 1?

**Comment by lxtGH** [comment]
Yes ~~ I set it to 1.

**Comment by ruotianluo** [comment]
Try to breakpoint and see what is going on.

**Comment by lxtGH** [comment]
A stupid action for me, I put the **pycocoevalcap** and **pycocotools**  in the main diretory and, I also put the coco-caption in the main diretory.
Now it works well !! Thanks again! 
By the way this project  implement 4 different models but not include this paper  Deep Visual-Semantic Alignments for Generating Image Descriptions ?  original neuraltalk?

**Comment by ruotianluo** [comment]
no neuraltalk.
