### ISSUE TITLE
how to control the num of thread?

### ISSUE THREAD

**Issue by qingchenwuhou** [ruotianluo/neuraltalk2.pytorch#21]
Hi, ruotian:

Thanks for your awesome code of reproducing the 'self-critical sequence training'.

I have a question that how to control the num of thread. When I run the code, all the threads are opened, and it occupy much cpu resource.

Thanks you!

**Comment by ruotianluo** [comment]
search num_workers in all files

**Comment by qingchenwuhou** [comment]
Okay, thanks.
