### ISSUE TITLE
performances of each model and self-critical

### ISSUE THREAD

**Issue by gctian** [ruotianluo/neuraltalk2.pytorch#26]
Dear @ruotianluo,
Thank you for your fantastic code. I have three problems:
1, I trained on my own dataset with top-dowm model.Would you please tell me the performances of each model on COCO dataset in models folder ? I read your document and just think the dop-dowm model performs best.
2, i don't find the process of image size when using resnet,and i resize the image 512*512 as input.
3, what is self-critical training? i don't find relevant parameters. I just find "Att2in model in self-critical" in Att2inModel.
Thank you again. I hope you don't mind so many questions and my poor english.  Look forward to communicating with you !

**Comment by ruotianluo** [comment]
1 what in the benchmark is what I tested. 
2 no resize is better 
3 in my another repository.  Self critucal

**Comment by gctian** [comment]
Thanks for your reply.At first i process image with no resize,but occur the exception “ cuda runtime error,out of memory!”,then i find some images is too large in my dataset.so i resize all images in 512*512.But there are only a few very large images.Do you have a better solution to this problem?

**Comment by ruotianluo** [comment]
It's never occured me, but yes if images are really large, it will be a problem. I would suggest resize the longest side to be less than 1000 or some thing like that.

**Comment by gctian** [comment]
good idea! Thank you,I will try.
