### ISSUE TITLE
some code missing?

### ISSUE THREAD

**Issue by cswhjiang** [ruotianluo/neuraltalk2.pytorch#3]
``` python scripts/prepro_labels.py --input_json .../dataset_coco.json --output_json data/cocotalk.json --output_h5 data/cocotalk ``` failed. Here are the errors:

```
Traceback (most recent call last):
  File "scripts/prepro_labels.py", line 192, in <module>
    main(params)
  File "scripts/prepro_labels.py", line 138, in main
    imgs = imgs['images']
TypeError: list indices must be integers, not str
```

It seems that some code is missing.

**Comment by ruotianluo** [comment]
Did you change `--input_json .../dataset_coco.json` to your own path?

**Comment by cswhjiang** [comment]
Thanks. I found the reason just now.

**Comment by brisker** [comment]
@ruotianluo 
for the "show_attend_tell" model, where is the code that visualize the visual attention on the input image?

**Comment by ruotianluo** [comment]
Sadly no, because I feel like it will be a little bit messy to add it.
But in principle, you can always save the alphas as a member variable, and visualize it using the code in arctic-caption.

**Comment by brisker** [comment]
@ruotianluo 
these lines in code for show_attend_tell [here](https://github.com/ruotianluo/neuraltalk2.pytorch/blob/master/models/CaptionModel.py#L248), it seems that there exist **no codes** that takes the attention into LSTM , since there is not any loops in your code,  but in another tensorflow implementation [here](https://github.com/yunjey/show-attend-and-tell/blob/master/core/model.py#L168), the author just take every word's attention into the LSTM in each step in a loop. So have I understand any wrong?

**Comment by brisker** [comment]
@ruotianluo 
I do not quite understand what you mean...
**what is "alphas"?
what is ‘arctic-caption“?**

**Comment by ruotianluo** [comment]
Sorry, what I means alpha is the attention map which is named as weight in my code.
alphas: https://github.com/ruotianluo/neuraltalk2.pytorch/blob/master/models/CaptionModel.py#L269
arctic-caption: https://github.com/kelvinxu/arctic-captions/blob/master/alpha_visualization.ipynb

You can save the weights at each timestep, and visualize it using the last block of the alpha_visualization.ipynb

**Comment by brisker** [comment]
@ruotianluo 
why using         ```
self.rnn = getattr(nn, self.rnn_type.upper())(self.input_encoding_size + self.att_feat_size, 
                self.rnn_size, self.num_layers, bias=False, dropout=self.drop_prob_lm)
```
[here](https://github.com/ruotianluo/neuraltalk2.pytorch/blob/master/models/CaptionModel.py#L238)?
why not directly using nn.LSTM?

**Comment by ruotianluo** [comment]
@brisker In principle it allows you to use GRU instead of LSTM, however I forgot if I tested or not.

**Comment by brisker** [comment]
@ruotianluo 
?？？ GRU or LSTM, it is decided by opt.rnn_type, right?

**Comment by ruotianluo** [comment]
@brisker Why not?

**Comment by brisker** [comment]
@ruotianluo 
new to image caption..
three questions
1. what does this variable [ss_prob](https://github.com/ruotianluo/neuraltalk2.pytorch/blob/master/models/CaptionModel.py#L31) mean?
2. what is the function of the variable [sample_mask](https://github.com/ruotianluo/neuraltalk2.pytorch/blob/master/models/CaptionModel.py#L62) ?

**Comment by ruotianluo** [comment]
schedule sampling
masks indicate how long each caption is.

**Comment by brisker** [comment]
@ruotianluo 
 the attention map which is named as weight in your code:
alphas: https://github.com/ruotianluo/neuraltalk2.pytorch/blob/master/models/CaptionModel.py#L269
did you mean that by just resizing the "weight" variable to the size of the input image, and then we can get the attention that is ready to be added to the input image for visualization?

**Comment by ruotianluo** [comment]
@brisker yes. Note that weight is flattened, you should first resize to 7x7. (I forgot to mention, this show_attend_tell is not exactly the same as described in the paper, it's simplified a little bit.)

**Comment by brisker** [comment]
@ruotianluo 
I am new to image caption...
could you please specify a little bit about where is the simplification in your code for the show_attend_tell model , comparing to the original paper?
[here ](https://github.com/ruotianluo/neuraltalk2.pytorch/blob/with_finetune/train.py#L140) ?
```
att_feats = cnn_model(images).permute(0, 2, 3, 1)
fc_feats = att_feats.mean(2).mean(1)
```

**Comment by ruotianluo** [comment]
@brisker This is because I'm using resnet.
The network details are different, but the main difference is I didn't add the doubly stochastic attention in the paper.

**Comment by brisker** [comment]
@ruotianluo 
do you mean that by setting [schedule sampling probability](https://github.com/ruotianluo/neuraltalk2.pytorch/blob/with_finetune/models/CaptionModel.py#L31) to a value larger than 0.0, then the model  is a Stochastic “Hard” Attention model depicted in the show_attend_tell paper?

**Comment by ruotianluo** [comment]
No, schedule sampling is another thing which is not mentioned in the show attend tell paper; you can google the schedule sampling paper;
I forgot to mention, hard attention is also one thing I didn't implement here.

**Comment by brisker** [comment]
@ruotianluo 
1. did you mean that the  schedule sampling paper is only corresponding to 
these codes?
```
            if self.training and i >= 1 and self.ss_prob > 0.0: # otherwiste no need to sample
                sample_prob = fc_feats.data.new(batch_size).uniform_(0, 1)

                #print("sample_prob:")
                #print(sample_prob.size())
                sample_mask = sample_prob < self.ss_prob
                if sample_mask.sum() == 0:
                    it = seq[:, i].clone()
                else:
                    sample_ind = sample_mask.nonzero().view(-1)
                    it = seq[:, i].data.clone()
                    #prob_prev = torch.exp(outputs[-1].data.index_select(0, sample_ind)) # fetch prev distribution: shape Nx(M+1)
                    #it.index_copy_(0, sample_ind, torch.multinomial(prob_prev, 1).view(-1))
                    prob_prev = torch.exp(outputs[-1].data) # fetch prev distribution: shape Nx(M+1)
                    it.index_copy_(0, sample_ind, torch.multinomial(prob_prev, 1).view(-1).index_select(0, sample_ind))
                    it = Variable(it, requires_grad=False)
```
2. what is the benefits of schedule sampling?

**Comment by ruotianluo** [comment]
Yes, it's replacing the input of network with sampled output by chance.
It's designed to solve the problem of test training discrepancy.
In practice, its effect depends on different model, like FCModel doesn't need scheduled sampling but ShowTell will perform better with scheduled sampling.

**Comment by brisker** [comment]
@ruotianluo 
so weird and embarrassed to ask, but when I am doing inference using the same model and the same image, why the inference results are different from each other?

**Comment by ruotianluo** [comment]
Did you set model to evaluate?

**Comment by brisker** [comment]
@ruotianluo 
yes

**Comment by ruotianluo** [comment]
How different are the results

**Comment by brisker** [comment]
@ruotianluo 
I am not using coco dataset, I am using my own dataset. The result seems to be very different......

**Comment by brisker** [comment]
@ruotianluo 
technically, in an attention model, the "att_feats" (output of cnn) and the LSTM hidden states **do not have to be concatenated**, right?

**Comment by ruotianluo** [comment]
Yes, as long as its mathematically equivalent.

**Comment by brisker** [comment]
@ruotianluo 
so what is the key idea of attention model? dynamically using the fc_feats and the LSTM hidden states to compute a weight tensor, and visualize this weight tensor on the input image?

**Comment by ruotianluo** [comment]
Idea is you can look at different part of the image at each time step.

**Comment by brisker** [comment]
@ruotianluo 
so you mean that every time step, we use the fc_feats and the LSTM hidden  states to compute the attention "weight" tensor, and every time step, the fc_feats [here](https://github.com/ruotianluo/neuraltalk2.pytorch/blob/master/models/OldModel.py#L203) is different? But actually it is the same, right? I am a little puzzled here.. which variable's change leads to "look at different part of the image at each time step"

**Comment by ruotianluo** [comment]
We don't use fc_feats to compute the weight, we use att_feats. hidden state is changing.

**Comment by brisker** [comment]
@ruotianluo 
so it's the hidden state changes lead to "look at different part of the image at each time step" ?  But actually att_feats does not change during the unrolling process of LSTM, right? **So the claim "look at different part of the image at each time step" is actually just a visualization ?**

**Comment by ruotianluo** [comment]
Att_feats are changing over locations, hidden states are changing over time. And the output of the attention module is a weighted summation of att_feats

**Comment by ruotianluo** [comment]
Technically I don't concat but mathematical it's equivalent. I wrote in this way to avoid duplicate computation.

**Comment by brisker** [comment]
@ruotianluo 
here :-- https://github.com/ruotianluo/neuraltalk2.pytorch/blob/master/models/OldModel.py#L224
```
 att_feats_ = att_feats.view(-1, att_size, self.att_feat_size) # batch * att_size * att_feat_size
att_res = torch.bmm(weight.unsqueeze(1), att_feats_).squeeze(1) # batch * att_feat_size output, state = self.rnn(torch.cat([xt, att_res], 1).unsqueeze(0), state)
```
xt is hidden state and att_res is a weighted sum of att_feats, right?
But if I do not concat xt and att_res, there is obviously no weighted sum of att_feats, right? Is this reasonable?

**Comment by ruotianluo** [comment]
Ok, it seems that I misunderstood your question. Yes, if you don't concat att_res here, it's not an attention model, and there's no visualization either, because there's no training signal to the attention module.

**Comment by brisker** [comment]
@ruotianluo 
so it is a must to combine both the output of LSTM and att_feats, in attention model.  Thanks. Besides, is there any other operations to combine this two variable, except concat?
