### ISSUE TITLE
I cannot reach the score where "readme.md“ mentioned.

### ISSUE THREAD

**Issue by LaiPiXiong** [ruotianluo/neuraltalk2.pytorch#53]
Hi, I use parameters as follows:(ShowAndTell)
CNN:  resnet152
LSTM: 2 Layers
other paramters are same as you mentioned, but the CIDEr score is only 0.681
And when change resnet152 to InceptionV4, the CIDEr score is only 0.651.
Both of them are far away from 0.84 which you mentioned in train parts.
Can you give me some advice on this score? I have tried lots of different parameters, but the score is  still low.

**Comment by ruotianluo** [comment]
Did you use the pretrained model weights I provide?

**Comment by LaiPiXiong** [comment]
Yes, I download it. And I submit the result to CodaLab, the score is only about 0.658( The best score I ever got)

**Comment by ruotianluo** [comment]
What's your local score.

**Comment by LaiPiXiong** [comment]
That's seem as you said in 'readme' in train part.
