### ISSUE TITLE
dataloaderraw.py, line 25 - IOError: [Errno 2] No such file or directory: '/home-nfs/rluo/rluo/model/pytorch-resnet/resnet101.pth'

### ISSUE THREAD

**Issue by Leinadho** [ruotianluo/neuraltalk2.pytorch#7]
This access of an absolute directory throws an error unless on rluo's account. 
Not difficult to manually fix for a user, but just thought I'd flag it.

**Comment by ruotianluo** [comment]
Specified the pretrained model location.
